[workspace]
members = ["rust/nature_remo_api", "rust/nature_remo_api_client"]
resolver = "3"
#members = ["rust/*"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 1

[workspace.package]
version = "0.1.4"
edition = "2024"

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
eyre = { version = "0.6" }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = "1.44"
http = "1.2"
thiserror = "2.0"
reqwest = { version = "0.12", features = ["json"] }