[workspace]
members = ["rust/nature_remo_api", "rust/nature_remo_api_raw", "rust/nature_remo_api_machine"]
resolver = "3"
#members = ["rust/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

