# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task sync
    silent: true
  init:
    cmds:
      - uv sync
      - cargo test
  test:
    cmds:
      - task: test_rs
      - task: test_py
  format:
    cmds:
      - task: format_rs
      - task: format_py
  # Rust ===================================================================-
  test_rs:
    cmds:
      - cargo test
  format_rs:
    cmds:
      - cargo clippy --workspace --exclude nature_remo_api_client --fix --allow-dirty --allow-staged
      - cargo clippy --workspace --exclude nature_remo_api_client --fix --allow-dirty --allow-staged --features="clippy"
      - cargo fmt --all
  format_rs_cli:
    cmds:
      - cargo clippy --workspace --exclude nature_remo_api --fix --allow-dirty --allow-staged --all-features --verbose
  run_rs:
    cmds:
      - RUST_LOG=info cargo run
  run_rs_debug:
    cmds:
      - RUST_LOG=debug cargo run --features "debug"
  # Python and Maturin =====================================================-
  sync:
    cmds:
      - uv sync --all-extras
      - uv run maturin develop
      #      - uv run maturin build --release
  test_py:
    cmds:
      - uv run pytest
  format_py:
    cmds:
      - uv run ruff format ./python
  run_py:
    cmds:
      - task: sync
      - uv run python ./bin/cli.py
