__name__ = "nature-remo"
__version__ = "0.1.3"
__author__ = "kkiyama117"
__author_email__ = "k.kiyama117@gmail.com"
__license__ = "MIT"
__description__ = "Python client for Nature Remo API"
__URL__ = "https://github.com/kkiyama117/hacs-nature-remo2"
